project:
  type: website
  output-dir: docs
website:
  title: "Koen Berben"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - text: Projects
        menu:
          - href: projects_BSc_thesis.qmd
            text: BSc thesis (2022) - Webscraping and Sentiment Analysis
          - href: project_BA.qmd
            text: MSc (2025) - Machine Learning for Business Analytics 
          - href: projects_webscraping_UN.qmd
            text: MSc (2025) - Webscraping and Text Mining
  page-footer:
    left: "Â© 2025 Koen Berben"
    right:
      - icon: github
        href: https://github.com/KBerben
      - icon: linkedin
        href: https://linkedin.com/in/koenberben
format:
    html:
      theme: cosmo
      css: styles.css
